# Generated by Django 5.0.2 on 2024-02-13 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NTN",
            fields=[
                ("ntn", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Anomaly",
            fields=[
                (
                    "srb_invoice_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("pos_id", models.IntegerField()),
                ("invoice_date", models.DateTimeField()),
                ("invoice_no", models.BigIntegerField()),
                ("rate_value", models.FloatField()),
                ("sales_value", models.FloatField()),
                ("sales_tax", models.FloatField()),
                ("consumer_name", models.CharField(max_length=256, null=True)),
                ("consumer_ntn", models.IntegerField(null=True)),
                ("consumer_address", models.CharField(max_length=256, null=True)),
                ("tariff_code", models.IntegerField(null=True)),
                ("extra_info", models.CharField(max_length=256, null=True)),
                ("pos_user", models.CharField(max_length=256)),
                ("pos_pass", models.CharField(max_length=256, null=True)),
                ("is_active", models.BooleanField()),
                ("created_date_time", models.DateTimeField()),
                ("invoice_type", models.IntegerField()),
                ("consider_for_annex", models.IntegerField()),
                ("anomaly", models.BooleanField()),
                (
                    "ntn_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="myapp.ntn"
                    ),
                ),
            ],
        ),
    ]
