# Generated by Django 5.0.2 on 2024-02-28 17:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnomalyInfo",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="NTN",
            fields=[
                ("ntn", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=256)),
                ("location", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="MissingInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoices",
                    models.CharField(
                        max_length=256,
                        validators=[django.core.validators.int_list_validator],
                    ),
                ),
                ("date", models.DateField()),
                (
                    "ntn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="myapp.ntn"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Anomaly",
            fields=[
                (
                    "srb_invoice_id",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                ("pos_id", models.IntegerField()),
                ("invoice_date", models.DateTimeField()),
                ("invoice_no", models.CharField(max_length=256)),
                ("rate_value", models.FloatField()),
                ("sales_value", models.FloatField()),
                ("sales_tax", models.FloatField()),
                ("consumer_name", models.CharField(max_length=256, null=True)),
                ("consumer_ntn", models.IntegerField(null=True)),
                ("consumer_address", models.CharField(max_length=256, null=True)),
                ("tariff_code", models.IntegerField(null=True)),
                ("extra_info", models.CharField(max_length=256, null=True)),
                ("pos_user", models.CharField(max_length=256, null=True)),
                ("pos_pass", models.CharField(max_length=256, null=True)),
                ("is_active", models.BooleanField()),
                ("created_date_time", models.DateTimeField()),
                ("invoice_type", models.IntegerField()),
                ("consider_for_annex", models.IntegerField(null=True)),
                (
                    "anomaly",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="myapp.anomalyinfo",
                    ),
                ),
                (
                    "ntn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="myapp.ntn"
                    ),
                ),
            ],
        ),
    ]
