# Generated by Django 5.0.2 on 2024-03-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anomaly",
            name="tariff_code",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
