# Generated by Django 5.0.2 on 2024-02-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anomaly",
            name="anomaly",
            field=models.BooleanField(default=False),
        ),
    ]
