# Generated by Django 5.0.2 on 2024-02-23 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_alter_anomaly_anomaly"),
    ]

    operations = [
        migrations.CreateModel(
            name="MissingInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice", models.IntegerField()),
                ("date", models.DateTimeField()),
                (
                    "ntn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="myapp.ntn"
                    ),
                ),
            ],
        ),
    ]
