# Generated by Django 5.0.2 on 2024-03-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomaly',
            name='sales_tax',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='sales_value',
            field=models.FloatField(null=True),
        ),
    ]
