# Generated by Django 5.0.2 on 2024-02-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_missinginvoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="ntn",
            name="location",
            field=models.CharField(default="Karachi", max_length=256),
            preserve_default=False,
        ),
    ]
