# Generated by Django 5.0.2 on 2024-03-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_alter_anomaly_options_alter_anomalyinfo_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anomaly",
            name="invoice_no",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
