# Generated by Django 5.0.2 on 2024-03-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_alter_anomaly_invoice_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anomaly",
            name="invoice_type",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
