# Generated by Django 5.0.2 on 2024-02-24 10:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_ntn_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="missinginvoice",
            name="invoice",
        ),
        migrations.AddField(
            model_name="missinginvoice",
            name="invoices",
            field=models.CharField(
                default=[1, 2],
                max_length=256,
                validators=[django.core.validators.int_list_validator],
            ),
            preserve_default=False,
        ),
    ]
