# Generated by Django 5.0.2 on 2024-03-19 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_anomaly_sales_tax_alter_anomaly_sales_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='missinginvoice',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missinginvoice',
            name='pos_id',
            field=models.IntegerField(default=44),
            preserve_default=False,
        ),
    ]
