# Generated by Django 5.0.2 on 2024-03-19 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_missinginvoice_location_missinginvoice_pos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missinginvoice',
            name='invoices',
            field=models.CharField(max_length=10000, validators=[django.core.validators.int_list_validator]),
        ),
    ]
