# Generated by Django 5.0.2 on 2024-02-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_remove_missinginvoice_invoice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missinginvoice",
            name="date",
            field=models.DateField(),
        ),
    ]
