# Generated by Django 5.0.2 on 2024-02-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_alter_missinginvoice_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="anomaly",
            old_name="ntn_id",
            new_name="ntn",
        ),
        migrations.AlterField(
            model_name="anomaly",
            name="consider_for_annex",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="anomaly",
            name="invoice_no",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="anomaly",
            name="pos_user",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="anomaly",
            name="srb_invoice_id",
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
